### ISSUE TITLE
Backslash escaping #s isn't valid JSON

### ISSUE THREAD

**Issue by v21** [galaxykate/tracery#13]
So the escape sequence for including a literal # is `\#`, right? Unfortunately, in JSON, that can only be used to escape a small range of things. JSON support seems like a valuable thing - it certainly simplifies giving as-you-type feedback in CBDQ. Is there a way we can change this to be JSON compatible?

**Comment by v21** [comment]
Oh, wait... `\\#` works...

**Comment by galaxykate** [comment]
Cool, LMK if you find other issues with the escape stuff (I tested it, but
I'm .... strangely unconfident that I got it right, especially for strange
use cases)

**Comment by gitkrax** [comment]
Has this changed somehow? I tried both `\#a` and `\\#a` and the result I get is `{{a}}` and `\{{a}}`.

**Comment by gitkrax** [comment]
I also noticed that trying the enter the unicode equivalent (`\u0023`) in tracery json creates problems. I haven't figured out how to debug this properly, but it seems that the parsing just stops if tracery encounters that unicode.
