### ISSUE TITLE
Feature request(?): change probabilities

### ISSUE THREAD

**Issue by shirish93** [galaxykate/tracery#23]
Hello,

I checked the documentation and was unable to find it, so this is probably a feature request. Does it make sense to add a feature to mess around with the likelihood of certain tokens? For example, if one wanted to make a faux astrology bot (not to give you any ideas, @dariusk ), and wanted to use some tokens ("Mars", "Venus") more than others?

THANKS!

Shirish

**Comment by dariusk** [comment]
@shirish93 What I would do is fake it by putting the same token multiple times.

`[a, a, b, b, c, d, e]` is not Tracery but illustrates what I'm talking about -- `a` and `b` are 2x as likely as `c` or `d` or `e`.

**Comment by Johnicholas** [comment]
I like using a function that takes a map and returns the repeated array
that Darius mentions.


function weighted(dict) {
  var out = []
  for (var key in dict) {
    for (var i = 0; i < dict[key]; i++) {
      out.push(key)
    }
  }
  return out
}


weighted({a: 2, b: 2, c: 1, d: 1, e: 1})


returns


[a, a, b, b, c, d, e]

**Comment by shirish93** [comment]
Fair. Closing the issue. Thanks everyone!
