### ISSUE TITLE
Add uppercase and lowercase modifiers

### ISSUE THREAD

**Issue by hugovk** [galaxykate/tracery#24]
There's already [`capitalize`](https://beaugunderson.com/tracery-writer/#?grammar=%7B%0A++%22origin%22%3A+%5B%0A++++%22%23stuff.capitalize%23%22%0A++%5D%2C%0A++%22stuff%22%3A+%5B%0A++++%22%23color%23+%23animal.s%23%22%0A++%5D%2C%0A++%22color%22%3A+%5B%0A++++%22orange%22%2C%0A++++%22blue%22%2C%0A++++%22white%22%2C%0A++++%22black%22%2C%0A++++%22grey%22%2C%0A++++%22purple%22%2C%0A++++%22indigo%22%2C%0A++++%22turquoise%22%0A++%5D%2C%0A++%22animal%22%3A+%5B%0A++++%22unicorn%22%2C%0A++++%22raven%22%2C%0A++++%22sparrow%22%2C%0A++++%22scorpion%22%2C%0A++++%22coyote%22%2C%0A++++%22eagle%22%2C%0A++++%22owl%22%2C%0A++++%22lizard%22%2C%0A++++%22zebra%22%2C%0A++++%22duck%22%2C%0A++++%22kitten%22%0A++%5D%0A%7D) and [`capitalizeAll`](https://beaugunderson.com/tracery-writer/#?grammar=%7B%0A++%22origin%22%3A+%5B%0A++++%22%23stuff.capitalizeAll%23%22%0A++%5D%2C%0A++%22stuff%22%3A+%5B%0A++++%22%23color%23+%23animal.s%23%22%0A++%5D%2C%0A++%22color%22%3A+%5B%0A++++%22orange%22%2C%0A++++%22blue%22%2C%0A++++%22white%22%2C%0A++++%22black%22%2C%0A++++%22grey%22%2C%0A++++%22purple%22%2C%0A++++%22indigo%22%2C%0A++++%22turquoise%22%0A++%5D%2C%0A++%22animal%22%3A+%5B%0A++++%22unicorn%22%2C%0A++++%22raven%22%2C%0A++++%22sparrow%22%2C%0A++++%22scorpion%22%2C%0A++++%22coyote%22%2C%0A++++%22eagle%22%2C%0A++++%22owl%22%2C%0A++++%22lizard%22%2C%0A++++%22zebra%22%2C%0A++++%22duck%22%2C%0A++++%22kitten%22%0A++%5D%0A%7D) modifiers which produce output like "Black unicorns" and "Black Unicorns" respectively.

How about [`upper`](https://beaugunderson.com/tracery-writer/#?grammar=%7B%0A++%22origin%22%3A+%5B%0A++++%22%23stuff.upper%23%22%0A++%5D%2C%0A++%22stuff%22%3A+%5B%0A++++%22%23color%23+%23animal.s%23%22%0A++%5D%2C%0A++%22color%22%3A+%5B%0A++++%22orange%22%2C%0A++++%22blue%22%2C%0A++++%22white%22%2C%0A++++%22black%22%2C%0A++++%22grey%22%2C%0A++++%22purple%22%2C%0A++++%22indigo%22%2C%0A++++%22turquoise%22%0A++%5D%2C%0A++%22animal%22%3A+%5B%0A++++%22unicorn%22%2C%0A++++%22raven%22%2C%0A++++%22sparrow%22%2C%0A++++%22scorpion%22%2C%0A++++%22coyote%22%2C%0A++++%22eagle%22%2C%0A++++%22owl%22%2C%0A++++%22lizard%22%2C%0A++++%22zebra%22%2C%0A++++%22duck%22%2C%0A++++%22kitten%22%0A++%5D%0A%7D) and [`lower`](https://beaugunderson.com/tracery-writer/#?grammar=%7B%0A++%22origin%22%3A+%5B%0A++++%22%23stuff.lower%23%22%0A++%5D%2C%0A++%22stuff%22%3A+%5B%0A++++%22%23color%23+%23animal.s%23%22%0A++%5D%2C%0A++%22color%22%3A+%5B%0A++++%22orange%22%2C%0A++++%22blue%22%2C%0A++++%22white%22%2C%0A++++%22black%22%2C%0A++++%22grey%22%2C%0A++++%22purple%22%2C%0A++++%22indigo%22%2C%0A++++%22turquoise%22%0A++%5D%2C%0A++%22animal%22%3A+%5B%0A++++%22unicorn%22%2C%0A++++%22raven%22%2C%0A++++%22sparrow%22%2C%0A++++%22scorpion%22%2C%0A++++%22coyote%22%2C%0A++++%22eagle%22%2C%0A++++%22owl%22%2C%0A++++%22lizard%22%2C%0A++++%22zebra%22%2C%0A++++%22duck%22%2C%0A++++%22kitten%22%0A++%5D%0A%7D) (or [`uppercase`](https://beaugunderson.com/tracery-writer/#?grammar=%7B%0A++%22origin%22%3A+%5B%0A++++%22%23stuff.uppercase%23%22%0A++%5D%2C%0A++%22stuff%22%3A+%5B%0A++++%22%23color%23+%23animal.s%23%22%0A++%5D%2C%0A++%22color%22%3A+%5B%0A++++%22orange%22%2C%0A++++%22blue%22%2C%0A++++%22white%22%2C%0A++++%22black%22%2C%0A++++%22grey%22%2C%0A++++%22purple%22%2C%0A++++%22indigo%22%2C%0A++++%22turquoise%22%0A++%5D%2C%0A++%22animal%22%3A+%5B%0A++++%22unicorn%22%2C%0A++++%22raven%22%2C%0A++++%22sparrow%22%2C%0A++++%22scorpion%22%2C%0A++++%22coyote%22%2C%0A++++%22eagle%22%2C%0A++++%22owl%22%2C%0A++++%22lizard%22%2C%0A++++%22zebra%22%2C%0A++++%22duck%22%2C%0A++++%22kitten%22%0A++%5D%0A%7D)/[`lowercase`](https://beaugunderson.com/tracery-writer/#?grammar=%7B%0A++%22origin%22%3A+%5B%0A++++%22%23stuff.lowercase%23%22%0A++%5D%2C%0A++%22stuff%22%3A+%5B%0A++++%22%23color%23+%23animal.s%23%22%0A++%5D%2C%0A++%22color%22%3A+%5B%0A++++%22orange%22%2C%0A++++%22blue%22%2C%0A++++%22white%22%2C%0A++++%22black%22%2C%0A++++%22grey%22%2C%0A++++%22purple%22%2C%0A++++%22indigo%22%2C%0A++++%22turquoise%22%0A++%5D%2C%0A++%22animal%22%3A+%5B%0A++++%22unicorn%22%2C%0A++++%22raven%22%2C%0A++++%22sparrow%22%2C%0A++++%22scorpion%22%2C%0A++++%22coyote%22%2C%0A++++%22eagle%22%2C%0A++++%22owl%22%2C%0A++++%22lizard%22%2C%0A++++%22zebra%22%2C%0A++++%22duck%22%2C%0A++++%22kitten%22%0A++%5D%0A%7D) or something) to produce "BLACK UNICORNS" and "black unicorns"?

**Comment by mycaule** [comment]
Hello you can reuse a string libary to do most common operations:

https://www.npmjs.com/package/string
https://www.npmjs.com/package/voca

Here is a sample implementation using voca.js, I just merge the modifier object with the voca object to get all the voca functions for free to use in the grammar syntax of tracery.
https://github.com/mycaule/epures/tree/master/modifiers

**Comment by hugovk** [comment]
Thanks for the tip, that's useful for using it as a JS library!

My main reason for opening this was to be able to use it in @v21's excellent Cheap Bots, Done Quick! where end users can only enter the Tracery grammar. 

See https://github.com/v21/tracery/pull/4
