### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by eykd** [galaxykate/tracery#6]
I just discovered your library, and I love the idea of it, but I don't see a license mentioned anywhere in the documentation or code. Unfortunately I really can't (legally) do anything with it unless you explicitly license it! Please take a moment to [choose a license](http://choosealicense.com/) and add it to the repository in a `LICENSE` file. I (and I'm sure many others) would greatly appreciate it. Thanks in advance.

**Comment by elib** [comment]
I guess I jumped the gun porting this to Ruby.
But +1 to this request so I can make it into a ruby gem.

**Comment by eykd** [comment]
Oh hey, [Apache License 2.0](https://github.com/galaxykate/tracery/blob/master/LICENSE.MD) added 5 months ago. Thanks, @galaxykate!

**Comment by galaxykate** [comment]
Oh, yep, there should always be an apache license on it, but sometimes I
accidentally overwrite it when I check in a new version.   The intention is
that it's free/OS

**Comment by elib** [comment]
Sorry! Was looking at the `tracery2` branch.

**Comment by galaxykate** [comment]
Ah, I must've forgotten to add the license there. Will do right away Thanks.
